CREATE TABLE Users
(
	Id int IDENTITY(1,1) PRIMARY KEY,
	UserName VARCHAR(50) UNIQUE NOT NULL DEFAULT '0',
	[Password] VARCHAR(130) NOT NULL DEFAULT '0',
	FullName VARCHAR(120) NOT NULL,
	RefreshToken VARCHAR(500) NULL DEFAULT '0',
	RefreshTokenExpiryTime DATETIME NULL DEFAULT NULL
)


